version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 515966531227.dkr.ecr.us-west-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t pong-game .
      - echo Tagging the Docker image...
      - docker tag pong-game:latest 515966531227.dkr.ecr.us-west-1.amazonaws.com/ping-pong-game-repo:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 515966531227.dkr.ecr.us-west-1.amazonaws.com/ping-pong-game-repo:latest
      - echo Creating imagedefinitions.json file for ECS deployment...
      - printf '[{"name":"pong-game","imageUri":"515966531227.dkr.ecr.us-west-1.amazonaws.com/ping-pong-game-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
